### ISSUE TITLE
Keg and beer view is broken somehow

### ISSUE THREAD

**Issue by stopthatcow** [Stonelinks/kegeratorjs#10]
Seems like when the temp chart went in the keg and beer table views got screwed up. They don't load for me though the endpoints seem fine.

**Comment by Stonelinks** [comment]
shit, never tested that. wilco

Lucas Doyle -- stonelinks.org/luke <http://stonelinks.org/luke.html>

**Comment by Stonelinks** [comment]
fixed in... whatever i did last night

**Comment by Stonelinks** [comment]
d7b4c8c17e8efa2071e8be93c2b82f403f623b36
