### ISSUE TITLE
Any resource listing that comes back should have an explicit and immutable "id" field

### ISSUE THREAD

**Issue by Stonelinks** [Stonelinks/kegeratorjs#5]
Instead of the id of a resource being "by convention", IE the index of that particular resource in an array, prefer an explicit id field. UUID v4 format preferred.

**Comment by stopthatcow** [comment]
Would this be the ID you use to look up the resource in the url...i.e /kegs/2918345739475 where 2918345739475 is the uuid? Currently this uses the internal TinyDB ID.

**Comment by Stonelinks** [comment]
Yeah it would. So is TinyDB generating an ID for everything? Can we use
this in the API then?

Lucas Doyle -- stonelinks.org/luke <http://stonelinks.org/luke.html>

**Comment by stopthatcow** [comment]
done, in 2ad3118af509b310994da6963d31d27041e65b95
